models:
  inventory_dbt:

    staging:
      +schema: default_staging
      +materialized: view
      +tags: ["staging"]

    silver:
      +schema: default_silver
      +materialized: view
      +tags: ["silver", "cleaned"]

    gold:
      +schema: default_gold
      +materialized: table
      +tags: ["gold", "aggregated"]

    business:
      +schema: default_business
      +materialized: view
      +tags: ["business", "platinum"]