inventory_dbt:
  target: databricks_cluster
  outputs:
    databricks_cluster:
      type: databricks
      catalog: "{{ env_var('DBT_DATABRICKS_CATALOG') }}"
      schema: default
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      threads: 4